### ISSUE TITLE
message_status sometimes received, sometimes not..

### ISSUE THREAD

**Issue by zeljko-bulatovic** [soygul/gcm#21]
Hi,

Thanks for this great library.

I have issue, that sometimes i receive delivery status from device, and sometimes not. My request is: 

fcmMsg := &ccs.OutMsg{
		To:                       deviceID,
		Priority:                 "high",
		DeliveryReceiptRequested: true,
		DelayWhileIdle:           true,
		Data:                     data,
	}

data is map[string]string.

Any known issue about this?

**Comment by soygul** [comment]
Nope it should be fine. If there is any error receiving or sending message, it's returned to you.

GCM behavior might have changed since I implemented this library so check the GCM docs about delivery status notifications.

**Comment by zeljko-bulatovic** [comment]
Thanks for your info.
